package sami.uilanguage.fromui;

import java.util.UUID;

/**
 * Super class of all messages to UI
 *
 * @author pscerri
 */
public abstract class FromUiMessage {

    final protected UUID relevantToUiMessageId;
    final protected UUID relevantOutputEventId;
    final protected UUID missionId;
    // Was this message generated by system autonomoy? Used for log playback
    protected boolean generatedFromAutonomy = false;

    public FromUiMessage(UUID relevantToUiMessageId, UUID relevantOutputEventId, UUID missionId) {
        this.relevantToUiMessageId = relevantToUiMessageId;
        this.relevantOutputEventId = relevantOutputEventId;
        this.missionId = missionId;
    }

    public UUID getMissionId() {
        return missionId;
    }

    public UUID getRelevantOutputEventId() {
        return relevantOutputEventId;
    }

    public boolean getGeneratedFromAutonomy() {
        return generatedFromAutonomy;
    }

    public void setGeneratedFromAutonomy(boolean generatedFromAutonomy) {
        this.generatedFromAutonomy = generatedFromAutonomy;
    }
}
